<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Exception\AMQP;

use ButterAMQP\Exception\ConnectionException;

/**
 * @codeCoverageIgnore
 */
class ConnectionForcedException extends ConnectionException
{
}
