<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Exception\AMQP;

use ButterAMQP\Exception\ChannelException;

/**
 * @codeCoverageIgnore
 */
class ContentTooLargeException extends ChannelException
{
}
