<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\AMQP091\Framing\Method;

use ButterAMQP\AMQP091\Framing\Frame;
use ButterAMQP\Value;

/**
 * End a queue consumer.
 *
 * @codeCoverageIgnore
 */
class BasicCancel extends Frame
{
    /**
     * @var string
     */
    private $consumerTag;

    /**
     * @var bool
     */
    private $noWait;

    /**
     * @param int    $channel
     * @param string $consumerTag
     * @param bool   $noWait
     */
    public function __construct($channel, $consumerTag, $noWait)
    {
        $this->consumerTag = $consumerTag;
        $this->noWait = $noWait;

        parent::__construct($channel);
    }

    /**
     * ConsumerTag.
     *
     * @return string
     */
    public function getConsumerTag()
    {
        return $this->consumerTag;
    }

    /**
     * NoWait.
     *
     * @return bool
     */
    public function isNoWait()
    {
        return $this->noWait;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x3C\x00\x1E".
            Value\ShortStringValue::encode($this->consumerTag).
            Value\BooleanValue::encode($this->noWait);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
