<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\AMQP091\Framing\Method;

use ButterAMQP\AMQP091\Framing\Frame;
use ButterAMQP\Value;

/**
 * Acknowledge one or more messages.
 *
 * @codeCoverageIgnore
 */
class BasicAck extends Frame
{
    /**
     * @var int
     */
    private $deliveryTag;

    /**
     * @var bool
     */
    private $multiple;

    /**
     * @param int  $channel
     * @param int  $deliveryTag
     * @param bool $multiple
     */
    public function __construct($channel, $deliveryTag, $multiple)
    {
        $this->deliveryTag = $deliveryTag;
        $this->multiple = $multiple;

        parent::__construct($channel);
    }

    /**
     * DeliveryTag.
     *
     * @return int
     */
    public function getDeliveryTag()
    {
        return $this->deliveryTag;
    }

    /**
     * Acknowledge multiple messages.
     *
     * @return bool
     */
    public function isMultiple()
    {
        return $this->multiple;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x3C\x00\x50".
            Value\LongLongValue::encode($this->deliveryTag).
            Value\BooleanValue::encode($this->multiple);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
