<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\AMQP091\Framing\Method;

use ButterAMQP\AMQP091\Framing\Frame;
use ButterAMQP\Value;

/**
 * Return a failed message.
 *
 * @codeCoverageIgnore
 */
class BasicReturn extends Frame
{
    /**
     * @var int
     */
    private $replyCode;

    /**
     * @var string
     */
    private $replyText;

    /**
     * @var string
     */
    private $exchange;

    /**
     * @var string
     */
    private $routingKey;

    /**
     * @param int    $channel
     * @param int    $replyCode
     * @param string $replyText
     * @param string $exchange
     * @param string $routingKey
     */
    public function __construct($channel, $replyCode, $replyText, $exchange, $routingKey)
    {
        $this->replyCode = $replyCode;
        $this->replyText = $replyText;
        $this->exchange = $exchange;
        $this->routingKey = $routingKey;

        parent::__construct($channel);
    }

    /**
     * ReplyCode.
     *
     * @return int
     */
    public function getReplyCode()
    {
        return $this->replyCode;
    }

    /**
     * ReplyText.
     *
     * @return string
     */
    public function getReplyText()
    {
        return $this->replyText;
    }

    /**
     * Exchange.
     *
     * @return string
     */
    public function getExchange()
    {
        return $this->exchange;
    }

    /**
     * Message routing key.
     *
     * @return string
     */
    public function getRoutingKey()
    {
        return $this->routingKey;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x3C\x00\x32".
            Value\ShortValue::encode($this->replyCode).
            Value\ShortStringValue::encode($this->replyText).
            Value\ShortStringValue::encode($this->exchange).
            Value\ShortStringValue::encode($this->routingKey);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
