<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\AMQP091\Framing\Method;

use ButterAMQP\AMQP091\Framing\Frame;
use ButterAMQP\Value;

/**
 * Propose connection tuning parameters.
 *
 * @codeCoverageIgnore
 */
class ConnectionTune extends Frame
{
    /**
     * @var int
     */
    private $channelMax;

    /**
     * @var int
     */
    private $frameMax;

    /**
     * @var int
     */
    private $heartbeat;

    /**
     * @param int $channel
     * @param int $channelMax
     * @param int $frameMax
     * @param int $heartbeat
     */
    public function __construct($channel, $channelMax, $frameMax, $heartbeat)
    {
        $this->channelMax = $channelMax;
        $this->frameMax = $frameMax;
        $this->heartbeat = $heartbeat;

        parent::__construct($channel);
    }

    /**
     * Proposed maximum channels.
     *
     * @return int
     */
    public function getChannelMax()
    {
        return $this->channelMax;
    }

    /**
     * Proposed maximum frame size.
     *
     * @return int
     */
    public function getFrameMax()
    {
        return $this->frameMax;
    }

    /**
     * Desired heartbeat delay.
     *
     * @return int
     */
    public function getHeartbeat()
    {
        return $this->heartbeat;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x0A\x00\x1E".
            Value\ShortValue::encode($this->channelMax).
            Value\LongValue::encode($this->frameMax).
            Value\ShortValue::encode($this->heartbeat);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
