<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\AMQP091\Framing\Method;

use ButterAMQP\AMQP091\Framing\Frame;
use ButterAMQP\Value;

/**
 * @codeCoverageIgnore
 */
class ConnectionBlocked extends Frame
{
    /**
     * @var string
     */
    private $reason;

    /**
     * @param int    $channel
     * @param string $reason
     */
    public function __construct($channel, $reason)
    {
        $this->reason = $reason;

        parent::__construct($channel);
    }

    /**
     * Reason.
     *
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x0A\x00\x3C".
            Value\ShortStringValue::encode($this->reason);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
