<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\AMQP091\Framing\Method;

use ButterAMQP\AMQP091\Framing\Frame;
use ButterAMQP\Value;

/**
 * Confirms a queue purge.
 *
 * @codeCoverageIgnore
 */
class QueuePurgeOk extends Frame
{
    /**
     * @var int
     */
    private $messageCount;

    /**
     * @param int $channel
     * @param int $messageCount
     */
    public function __construct($channel, $messageCount)
    {
        $this->messageCount = $messageCount;

        parent::__construct($channel);
    }

    /**
     * MessageCount.
     *
     * @return int
     */
    public function getMessageCount()
    {
        return $this->messageCount;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x32\x00\x1F".
            Value\LongValue::encode($this->messageCount);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
