<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\AMQP091\Framing\Method;

use ButterAMQP\AMQP091\Framing\Frame;
use ButterAMQP\Value;

/**
 * Purge a queue.
 *
 * @codeCoverageIgnore
 */
class QueuePurge extends Frame
{
    /**
     * @var int
     */
    private $reserved1;

    /**
     * @var string
     */
    private $queue;

    /**
     * @var bool
     */
    private $noWait;

    /**
     * @param int    $channel
     * @param int    $reserved1
     * @param string $queue
     * @param bool   $noWait
     */
    public function __construct($channel, $reserved1, $queue, $noWait)
    {
        $this->reserved1 = $reserved1;
        $this->queue = $queue;
        $this->noWait = $noWait;

        parent::__construct($channel);
    }

    /**
     * Reserved1.
     *
     * @return int
     */
    public function getReserved1()
    {
        return $this->reserved1;
    }

    /**
     * Queue.
     *
     * @return string
     */
    public function getQueue()
    {
        return $this->queue;
    }

    /**
     * NoWait.
     *
     * @return bool
     */
    public function isNoWait()
    {
        return $this->noWait;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x32\x00\x1E".
            Value\ShortValue::encode($this->reserved1).
            Value\ShortStringValue::encode($this->queue).
            Value\BooleanValue::encode($this->noWait);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
