<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\AMQP091\Framing\Method;

use ButterAMQP\AMQP091\Framing\Frame;

/**
 * Abandon the current transaction.
 *
 * @codeCoverageIgnore
 */
class TxRollback extends Frame
{
    /**
     * @return string
     */
    public function encode()
    {
        return "\x01".pack('n', $this->channel)."\x00\x00\x00\x04\x00\x5A\x00\x1E\xCE";
    }
}
