<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Exception;

class AMQPException extends \Exception
{
    public static function make($message, $code)
    {
        switch ($code) {
            case 311: return new AMQP\ContentTooLargeException($message, $code);
            case 313: return new AMQP\NoConsumersException($message, $code);
            case 320: return new AMQP\ConnectionForcedException($message, $code);
            case 402: return new AMQP\InvalidPathException($message, $code);
            case 403: return new AMQP\AccessRefusedException($message, $code);
            case 404: return new AMQP\NotFoundException($message, $code);
            case 405: return new AMQP\ResourceLockedException($message, $code);
            case 406: return new AMQP\PreconditionFailedException($message, $code);
            case 501: return new AMQP\FrameErrorException($message, $code);
            case 502: return new AMQP\SyntaxErrorException($message, $code);
            case 503: return new AMQP\CommandInvalidException($message, $code);
            case 504: return new AMQP\ChannelErrorException($message, $code);
            case 505: return new AMQP\UnexpectedFrameException($message, $code);
            case 506: return new AMQP\ResourceErrorException($message, $code);
            case 530: return new AMQP\NotAllowedException($message, $code);
            case 540: return new AMQP\NotImplementedException($message, $code);
            case 541: return new AMQP\InternalErrorException($message, $code);
        }

        return new self($message, $code);
    }
}
