<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Buffer;
use ButterAMQP\Framing\Method;
use ButterAMQP\Value;

/**
 * Publish a message.
 *
 * @codeCoverageIgnore
 */
class BasicPublish extends Method
{
    /**
     * @var int
     */
    private $reserved1;

    /**
     * @var string
     */
    private $exchange;

    /**
     * @var string
     */
    private $routingKey;

    /**
     * @var bool
     */
    private $mandatory;

    /**
     * @var bool
     */
    private $immediate;

    /**
     * @param int    $reserved1
     * @param string $exchange
     * @param string $routingKey
     * @param bool   $mandatory
     * @param bool   $immediate
     */
    public function __construct($reserved1, $exchange, $routingKey, $mandatory, $immediate)
    {
        $this->reserved1 = $reserved1;
        $this->exchange = $exchange;
        $this->routingKey = $routingKey;
        $this->mandatory = $mandatory;
        $this->immediate = $immediate;
    }

    /**
     * Reserved1.
     *
     * @return int
     */
    public function getReserved1()
    {
        return $this->reserved1;
    }

    /**
     * Exchange.
     *
     * @return string
     */
    public function getExchange()
    {
        return $this->exchange;
    }

    /**
     * Message routing key.
     *
     * @return string
     */
    public function getRoutingKey()
    {
        return $this->routingKey;
    }

    /**
     * Indicate mandatory routing.
     *
     * @return bool
     */
    public function isMandatory()
    {
        return $this->mandatory;
    }

    /**
     * Request immediate delivery.
     *
     * @return bool
     */
    public function isImmediate()
    {
        return $this->immediate;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x3C\x00\x28".
            Value\ShortValue::encode($this->reserved1).
            Value\ShortStringValue::encode($this->exchange).
            Value\ShortStringValue::encode($this->routingKey).
            Value\OctetValue::encode(($this->mandatory ? 1 : 0) | (($this->immediate ? 1 : 0) << 1));
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\ShortValue::decode($data),
            Value\ShortStringValue::decode($data),
            Value\ShortStringValue::decode($data),
            (bool) ($flags = Value\OctetValue::decode($data)) & 1,
            (bool) $flags & 2
        );
    }
}
