<?php
/*
 * This file is automatically generated.
 */

namespace AMQPLib\Framing\Method;

use AMQPLib\Buffer;
use AMQPLib\Framing\Method;
use AMQPLib\Value;

/**
 * End a queue consumer.
 */
class BasicCancel extends Method
{
    /**
     * @var string
     */
    private $consumerTag;

    /**
     * @var bool
     */
    private $noWait;

    /**
     * @param string $consumerTag
     * @param bool   $noWait
     */
    public function __construct($consumerTag, $noWait)
    {
        $this->consumerTag = $consumerTag;
        $this->noWait = $noWait;
    }

    /**
     * ConsumerTag.
     *
     * @return string
     */
    public function getConsumerTag()
    {
        return $this->consumerTag;
    }

    /**
     * NoWait.
     *
     * @return bool
     */
    public function isNoWait()
    {
        return $this->noWait;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x3C\x00\x1E".
            Value\ShortStringValue::encode($this->consumerTag).
            Value\BooleanValue::encode($this->noWait);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\ShortStringValue::decode($data),
            Value\BooleanValue::decode($data)
        );
    }
}
