<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Framing\Frame;
use ButterAMQP\Value;

/**
 * Reject an incoming message.
 *
 * @codeCoverageIgnore
 */
class BasicReject extends Frame
{
    /**
     * @var int
     */
    private $deliveryTag;

    /**
     * @var bool
     */
    private $requeue;

    /**
     * @param int  $channel
     * @param int  $deliveryTag
     * @param bool $requeue
     */
    public function __construct($channel, $deliveryTag, $requeue)
    {
        $this->deliveryTag = $deliveryTag;
        $this->requeue = $requeue;

        parent::__construct($channel);
    }

    /**
     * DeliveryTag.
     *
     * @return int
     */
    public function getDeliveryTag()
    {
        return $this->deliveryTag;
    }

    /**
     * Requeue the message.
     *
     * @return bool
     */
    public function isRequeue()
    {
        return $this->requeue;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x3C\x00\x5A".
            Value\LongLongValue::encode($this->deliveryTag).
            Value\BooleanValue::encode($this->requeue);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
