<?php
/*
 * This file is automatically generated.
 */

namespace AMQPLib\Framing\Method;

use AMQPLib\Buffer;
use AMQPLib\Framing\Method;
use AMQPLib\Value;

/**
 * Reject one or more incoming messages.
 */
class BasicNack extends Method
{
    /**
     * @var int
     */
    private $deliveryTag;

    /**
     * @var bool
     */
    private $multiple;

    /**
     * @var bool
     */
    private $requeue;

    /**
     * @param int  $deliveryTag
     * @param bool $multiple
     * @param bool $requeue
     */
    public function __construct($deliveryTag, $multiple, $requeue)
    {
        $this->deliveryTag = $deliveryTag;
        $this->multiple = $multiple;
        $this->requeue = $requeue;
    }

    /**
     * DeliveryTag.
     *
     * @return int
     */
    public function getDeliveryTag()
    {
        return $this->deliveryTag;
    }

    /**
     * Reject multiple messages.
     *
     * @return bool
     */
    public function isMultiple()
    {
        return $this->multiple;
    }

    /**
     * Requeue the message.
     *
     * @return bool
     */
    public function isRequeue()
    {
        return $this->requeue;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x3C\x00\x78".
            Value\LongLongValue::encode($this->deliveryTag).
            Value\OctetValue::encode(($this->multiple ? 1 : 0) | (($this->requeue ? 1 : 0) << 1));
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\LongLongValue::decode($data),
            (bool) ($flags = Value\OctetValue::decode($data)) & 1,
            (bool) $flags & 2
        );
    }
}
