<?php
/*
 * This file is automatically generated.
 */

namespace AMQLib\Framing\Method;

use AMQLib\Buffer;
use AMQLib\Framing\Method;
use AMQLib\Value;

/**
 * Reject an incoming message.
 */
class BasicReject extends Method
{
    /**
     * @var int
     */
    private $deliveryTag;

    /**
     * @var bool
     */
    private $requeue;

    /**
     * @param int  $deliveryTag
     * @param bool $requeue
     */
    public function __construct($deliveryTag, $requeue)
    {
        $this->deliveryTag = $deliveryTag;
        $this->requeue = $requeue;
    }

    /**
     * DeliveryTag.
     *
     * @return int
     */
    public function getDeliveryTag()
    {
        return $this->deliveryTag;
    }

    /**
     * Requeue the message.
     *
     * @return bool
     */
    public function isRequeue()
    {
        return $this->requeue;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x3C\x00\x5A".
            Value\LongLongValue::encode($this->deliveryTag).
            Value\BooleanValue::encode($this->requeue);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\LongLongValue::decode($data),
            Value\BooleanValue::decode($data)
        );
    }
}
