<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Buffer;
use ButterAMQP\Framing\Method;
use ButterAMQP\Value;

/**
 * Redeliver unacknowledged messages.
 *
 * @codeCoverageIgnore
 */
class BasicRecover extends Method
{
    /**
     * @var bool
     */
    private $requeue;

    /**
     * @param bool $requeue
     */
    public function __construct($requeue)
    {
        $this->requeue = $requeue;
    }

    /**
     * Requeue the message.
     *
     * @return bool
     */
    public function isRequeue()
    {
        return $this->requeue;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x3C\x00\x6E".
            Value\BooleanValue::encode($this->requeue);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\BooleanValue::decode($data)
        );
    }
}
