<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Framing\Frame;
use ButterAMQP\Value;

/**
 * Confirm a new consumer.
 *
 * @codeCoverageIgnore
 */
class BasicConsumeOk extends Frame
{
    /**
     * @var string
     */
    private $consumerTag;

    /**
     * @param int    $channel
     * @param string $consumerTag
     */
    public function __construct($channel, $consumerTag)
    {
        $this->consumerTag = $consumerTag;

        parent::__construct($channel);
    }

    /**
     * ConsumerTag.
     *
     * @return string
     */
    public function getConsumerTag()
    {
        return $this->consumerTag;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x3C\x00\x15".
            Value\ShortStringValue::encode($this->consumerTag);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
