<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Framing\Frame;
use ButterAMQP\Value;

/**
 * Direct access to a queue.
 *
 * @codeCoverageIgnore
 */
class BasicGet extends Frame
{
    /**
     * @var int
     */
    private $reserved1;

    /**
     * @var string
     */
    private $queue;

    /**
     * @var bool
     */
    private $noAck;

    /**
     * @param int    $channel
     * @param int    $reserved1
     * @param string $queue
     * @param bool   $noAck
     */
    public function __construct($channel, $reserved1, $queue, $noAck)
    {
        $this->reserved1 = $reserved1;
        $this->queue = $queue;
        $this->noAck = $noAck;

        parent::__construct($channel);
    }

    /**
     * Reserved1.
     *
     * @return int
     */
    public function getReserved1()
    {
        return $this->reserved1;
    }

    /**
     * Queue.
     *
     * @return string
     */
    public function getQueue()
    {
        return $this->queue;
    }

    /**
     * NoAck.
     *
     * @return bool
     */
    public function isNoAck()
    {
        return $this->noAck;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x3C\x00\x46".
            Value\ShortValue::encode($this->reserved1).
            Value\ShortStringValue::encode($this->queue).
            Value\BooleanValue::encode($this->noAck);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
