<?php
/*
 * This file is automatically generated.
 */

namespace AMQLib\Framing\Method;

use AMQLib\Buffer;
use AMQLib\Framing\Method;
use AMQLib\Value;

/**
 * Direct access to a queue.
 */
class BasicGet extends Method
{
    /**
     * @var int
     */
    private $reserved1;

    /**
     * @var string
     */
    private $queue;

    /**
     * @var bool
     */
    private $noAck;

    /**
     * @param int    $reserved1
     * @param string $queue
     * @param bool   $noAck
     */
    public function __construct($reserved1, $queue, $noAck)
    {
        $this->reserved1 = $reserved1;
        $this->queue = $queue;
        $this->noAck = $noAck;
    }

    /**
     * Reserved1.
     *
     * @return int
     */
    public function getReserved1()
    {
        return $this->reserved1;
    }

    /**
     * Queue.
     *
     * @return string
     */
    public function getQueue()
    {
        return $this->queue;
    }

    /**
     * NoAck.
     *
     * @return bool
     */
    public function isNoAck()
    {
        return $this->noAck;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x3C\x00\x46".
            Value\ShortValue::encode($this->reserved1).
            Value\ShortStringValue::encode($this->queue).
            Value\BooleanValue::encode($this->noAck);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\ShortValue::decode($data),
            Value\ShortStringValue::decode($data),
            Value\BooleanValue::decode($data)
        );
    }
}
