<?php
/*
 * This file is automatically generated.
 */

namespace AMQLib\Framing\Method;

use AMQLib\Buffer;
use AMQLib\Framing\Method;
use AMQLib\Value;

/**
 * Confirm a flow method.
 *
 * @codeCoverageIgnore
 */
class ChannelFlowOk extends Method
{
    /**
     * @var bool
     */
    private $active;

    /**
     * @param bool $active
     */
    public function __construct($active)
    {
        $this->active = $active;
    }

    /**
     * Current flow setting.
     *
     * @return bool
     */
    public function isActive()
    {
        return $this->active;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x14\x00\x15".
            Value\BooleanValue::encode($this->active);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\BooleanValue::decode($data)
        );
    }
}
