<?php
/*
 * This file is automatically generated.
 */

namespace AMQPLib\Framing\Method;

use AMQPLib\Buffer;
use AMQPLib\Framing\Method;
use AMQPLib\Value;

/**
 * Signal that the channel is ready.
 */
class ChannelOpenOk extends Method
{
    /**
     * @var string
     */
    private $reserved1;

    /**
     * @param string $reserved1
     */
    public function __construct($reserved1)
    {
        $this->reserved1 = $reserved1;
    }

    /**
     * Reserved1.
     *
     * @return string
     */
    public function getReserved1()
    {
        return $this->reserved1;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x14\x00\x0B".
            Value\LongStringValue::encode($this->reserved1);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\LongStringValue::decode($data)
        );
    }
}
