<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Framing\Frame;

/**
 * Confirm a channel close.
 *
 * @codeCoverageIgnore
 */
class ChannelCloseOk extends Frame
{
    /**
     * @return string
     */
    public function encode()
    {
        return "\x01".pack('n', $this->channel)."\x00\x00\x00\x04\x00\x14\x00\x29\xCE";
    }
}
