<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Buffer;
use ButterAMQP\Framing\Method;
use ButterAMQP\Value;

/**
 * @codeCoverageIgnore
 */
class ConfirmSelect extends Method
{
    /**
     * @var bool
     */
    private $nowait;

    /**
     * @param bool $nowait
     */
    public function __construct($nowait)
    {
        $this->nowait = $nowait;
    }

    /**
     * Nowait.
     *
     * @return bool
     */
    public function isNowait()
    {
        return $this->nowait;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x55\x00\x0A".
            Value\BooleanValue::encode($this->nowait);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\BooleanValue::decode($data)
        );
    }
}
