<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Framing\Frame;
use ButterAMQP\Value;

/**
 * Security mechanism response.
 *
 * @codeCoverageIgnore
 */
class ConnectionSecureOk extends Frame
{
    /**
     * @var string
     */
    private $response;

    /**
     * @param int    $channel
     * @param string $response
     */
    public function __construct($channel, $response)
    {
        $this->response = $response;

        parent::__construct($channel);
    }

    /**
     * Security response data.
     *
     * @return string
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * @return string
     */
    public function encode()
    {
        $data = "\x00\x0A\x00\x15".
            Value\LongStringValue::encode($this->response);

        return "\x01".pack('nN', $this->channel, strlen($data)).$data."\xCE";
    }
}
