<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Buffer;
use ButterAMQP\Framing\Method;
use ButterAMQP\Value;

/**
 * Open connection to virtual host.
 *
 * @codeCoverageIgnore
 */
class ConnectionOpen extends Method
{
    /**
     * @var string
     */
    private $virtualHost;

    /**
     * @var string
     */
    private $reserved1;

    /**
     * @var bool
     */
    private $reserved2;

    /**
     * @param string $virtualHost
     * @param string $reserved1
     * @param bool   $reserved2
     */
    public function __construct($virtualHost, $reserved1, $reserved2)
    {
        $this->virtualHost = $virtualHost;
        $this->reserved1 = $reserved1;
        $this->reserved2 = $reserved2;
    }

    /**
     * Virtual host name.
     *
     * @return string
     */
    public function getVirtualHost()
    {
        return $this->virtualHost;
    }

    /**
     * Reserved1.
     *
     * @return string
     */
    public function getReserved1()
    {
        return $this->reserved1;
    }

    /**
     * Reserved2.
     *
     * @return bool
     */
    public function isReserved2()
    {
        return $this->reserved2;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x0A\x00\x28".
            Value\ShortStringValue::encode($this->virtualHost).
            Value\ShortStringValue::encode($this->reserved1).
            Value\BooleanValue::encode($this->reserved2);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\ShortStringValue::decode($data),
            Value\ShortStringValue::decode($data),
            Value\BooleanValue::decode($data)
        );
    }
}
