<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Buffer;
use ButterAMQP\Framing\Method;
use ButterAMQP\Value;

/**
 * Security mechanism response.
 *
 * @codeCoverageIgnore
 */
class ConnectionSecureOk extends Method
{
    /**
     * @var string
     */
    private $response;

    /**
     * @param string $response
     */
    public function __construct($response)
    {
        $this->response = $response;
    }

    /**
     * Security response data.
     *
     * @return string
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x0A\x00\x15".
            Value\LongStringValue::encode($this->response);
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\LongStringValue::decode($data)
        );
    }
}
