<?php
/*
 * This file is automatically generated.
 */

namespace AMQPLib\Framing\Method;

use AMQPLib\Buffer;
use AMQPLib\Framing\Method;

/**
 * Confirm bind successful.
 */
class ExchangeBindOk extends Method
{
    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x28\x00\x1F";
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self();
    }
}
