<?php
/*
 * This file is automatically generated.
 */

namespace AMQLib\Framing\Method;

use AMQLib\Buffer;
use AMQLib\Framing\Method;
use AMQLib\Value;

/**
 * Delete an exchange.
 */
class ExchangeDelete extends Method
{
    /**
     * @var int
     */
    private $reserved1;

    /**
     * @var string
     */
    private $exchange;

    /**
     * @var bool
     */
    private $ifUnused;

    /**
     * @var bool
     */
    private $noWait;

    /**
     * @param int    $reserved1
     * @param string $exchange
     * @param bool   $ifUnused
     * @param bool   $noWait
     */
    public function __construct($reserved1, $exchange, $ifUnused, $noWait)
    {
        $this->reserved1 = $reserved1;
        $this->exchange = $exchange;
        $this->ifUnused = $ifUnused;
        $this->noWait = $noWait;
    }

    /**
     * Reserved1.
     *
     * @return int
     */
    public function getReserved1()
    {
        return $this->reserved1;
    }

    /**
     * Exchange.
     *
     * @return string
     */
    public function getExchange()
    {
        return $this->exchange;
    }

    /**
     * Delete only if unused.
     *
     * @return bool
     */
    public function isIfUnused()
    {
        return $this->ifUnused;
    }

    /**
     * NoWait.
     *
     * @return bool
     */
    public function isNoWait()
    {
        return $this->noWait;
    }

    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x28\x00\x14".
            Value\ShortValue::encode($this->reserved1).
            Value\ShortStringValue::encode($this->exchange).
            Value\OctetValue::encode(($this->ifUnused ? 1 : 0) | (($this->noWait ? 1 : 0) << 1));
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self(
            Value\ShortValue::decode($data),
            Value\ShortStringValue::decode($data),
            (bool) ($flags = Value\OctetValue::decode($data)) & 1,
            (bool) $flags & 2
        );
    }
}
