<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Framing\Frame;

/**
 * Confirm exchange declaration.
 *
 * @codeCoverageIgnore
 */
class ExchangeDeclareOk extends Frame
{
    /**
     * @return string
     */
    public function encode()
    {
        return "\x01".pack('n', $this->channel)."\x00\x00\x00\x04\x00\x28\x00\x0B\xCE";
    }
}
