<?php
/*
 * This file is automatically generated.
 */

namespace ButterAMQP\Framing\Method;

use ButterAMQP\Framing\Frame;

/**
 * Confirm successful rollback.
 *
 * @codeCoverageIgnore
 */
class TxRollbackOk extends Frame
{
    /**
     * @return string
     */
    public function encode()
    {
        return "\x01".pack('n', $this->channel)."\x00\x00\x00\x04\x00\x5A\x00\x1F\xCE";
    }
}
