<?php
/*
 * This file is automatically generated.
 */

namespace AMQPLib\Framing\Method;

use AMQPLib\Buffer;
use AMQPLib\Framing\Method;

/**
 * Select standard transaction mode.
 */
class TxSelect extends Method
{
    /**
     * @return string
     */
    public function encode()
    {
        return "\x00\x5A\x00\x0A";
    }

    /**
     * @param Buffer $data
     *
     * @return $this
     */
    public static function decode(Buffer $data)
    {
        return new self();
    }
}
